name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to GCP Artifact Registry
      env: 
        keyfile: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |-
         echo ${keyfile} | docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t us-east1-docker.pkg.dev/base-image-451513/my-docker-repository/base-image:1.0 .

    - name: Push Docker Image to GCP Artifact Registry
      run: |
        docker push us-east1-docker.pkg.dev/base-image-451513/my-docker-repository/base-image:1.0
